---
# Ce fichier doit être chiffré avec ansible-vault :
#   ansible-vault encrypt ansible/inventory/group_vars/vault.yml
#
# Pour éditer après chiffrement :
#   ansible-vault edit ansible/inventory/group_vars/vault.yml

vault_db_password: "CHANGEME_mot_de_passe_postgres"
vault_app_secret: "CHANGEME_openssl_rand_base64_32"
vault_tchap_service_key: "CHANGEME_openssl_rand_hex_32"
