---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    prod:
      hosts:
        gestion-tchap:
          ansible_host: 192.168.1.10   # À remplacer par l'IP de votre VM
          ansible_port: 22
