---
- name: Suppression des anciennes versions de Docker
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - podman-docker
      - containerd
      - runc
    state: absent

- name: Ajout de la clé GPG officielle Docker
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Ajout du dépôt Docker
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ ansible_architecture | replace('x86_64','amd64') }}
      signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }} stable
    filename: docker
    state: present

- name: Installation Docker Engine + Compose plugin
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true
    state: present

- name: Activation et démarrage de Docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Ajout de l'utilisateur deploy au groupe docker
  ansible.builtin.user:
    name: "{{ deploy_user }}"
    groups: docker
    append: true
